{"name": "test_add_error", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('get_error_data', <FixtureRequest for <Function test_add_error>>)", "trace": "file C:\\Users\\zenghuan\\PycharmProjects\\ck22_20220113\\testing\\test_calc_fixture_param.py, line 91\n      @pytest.mark.run(order=3)\n      @allure.story('error测试用例')\n      def test_add_error(self, get_cacl, get_error_data):\nE       fixture 'get_error_data' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, get_cacl, get_data, get_data2, manage_logs, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, start, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\zenghuan\\PycharmProjects\\ck22_20220113\\testing\\test_calc_fixture_param.py:91"}, "start": 1645096470578, "stop": 1645096470578, "uuid": "0cbf6845-985c-420e-b8b7-5b9dc65eebce", "historyId": "51219c8e98591093de05131c9bc9b306", "testCaseId": "588ad8b39e9fdf0834c99e4de8c6c149", "fullName": "testing.test_calc_fixture_param.TestCalc#test_add_error", "labels": [{"name": "feature", "value": "计算器测试用例"}, {"name": "story", "value": "error测试用例"}, {"name": "tag", "value": "run(order=3)"}, {"name": "parentSuite", "value": "testing"}, {"name": "suite", "value": "test_calc_fixture_param"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "zenghuan-PC"}, {"name": "thread", "value": "14748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testing.test_calc_fixture_param"}]}